version: 2
jobs:
  build:
    machine:
      - enabled : true
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            echo Failed waiting for Rabbitmq

      - run:
          name: Run pre-commit to check lint, pydocstyle
          command: |
            echo "another run"
