version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Run pre-commit to check lint, pydocstyle
          command: |
            pip install pre-commit --user
            pre-commit run --all-files
















#      version: 2
#      jobs:
#        build:
#          machine: true
#      steps:
#        - checkout
#      - run:
#        name: install dependencies
#        command: |
#          uname -a
#
#      - run:
#        name: Run pre-commit to check lint, pydocstyle
#        command: |
#          echo "another run"
