
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
        name: install dependencies
        command: |
          curl https://pre-commit.com/install-local.py | python -

      - run:
        name: Run pre-commit to check lint, pydocstyle
        command: |
          pre-commit run --all-files
