version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            uname -a

      - run:
          name: Run pre-commit to check lint, pydocstyle
          command: |
            echo "another run"
