version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      #       # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      #             - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Run pre-commit to check lint, pydocstyle
          command: |
            pip install pre-commit
            pre-commit run --all-files
















#      version: 2
#      jobs:
#        build:
#          machine: true
#      steps:
#        - checkout
#      - run:
#        name: install dependencies
#        command: |
#          uname -a
#
#      - run:
#        name: Run pre-commit to check lint, pydocstyle
#        command: |
#          echo "another run"
