
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
            unzip terraform_0.11.11_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
            go get github.com/segmentio/terraform-docs
            curl https://pre-commit.com/install-local.py | python -

      - run:
          name: Run pre-commit to check lint, pydocstyle
          command: |
            pre-commit run --all-files
